;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        conf--backward-delete-word
        conf--meow-change-and-mark
        conf--meow-insert-wrap
        electric-pair-delete-pair
        end-of-buffer
        ignore
        indent-for-tab-command
        insert-pair
        kill-region-maybe
        mark-sexp
        markdown-beginning-of-line
        markdown-end-of-line
        markdown-outdent-or-delete
        meow-back-word
        meow-bounds-of-thing
        meow-cancel-selection
        meow-change
        meow-delete
        meow-insert
        meow-join
        meow-kill
        meow-left
        meow-line
        meow-mark-symbol
        meow-mark-word
        meow-next
        meow-next-symbol
        meow-next-word
        meow-prev
        meow-replace
        meow-right
        meow-till
        my-backward-kill-word
        org-end-of-line
        org-self-insert-command
        org-yank
        phi-search
        xref-go-back
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        conf--undo
        conf--vterm-toggle
        meow-insert-exit
        meow-keypad
        meow-undo
        mouse-set-region
        pixel-scroll-precision
        symbol-overlay-isearch-literally
        symbol-overlay-rename
        undefined
        undo-only
        wgrep-change-to-wgrep-mode
        wgrep-finish-edit
        ))
